on:
  - push
jobs:
  unittest:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          PR_NUMBER: ${{ github.event.number }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python -m pytest irsa/tests
        name: Test without Coverage
      - run: python -m pytest --cache-clear --cov=service irsa/tests > pytest-coverage.txt
        name: Unit testing & Coverage
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2